/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViceGovernador2RouteImport } from './routes/vice-governador-2'
import { Route as ViceGovernador1RouteImport } from './routes/vice-governador-1'
import { Route as TesoureiroRouteImport } from './routes/tesoureiro'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SecretarioRouteImport } from './routes/secretario'
import { Route as ProtocoloLeonisticoRouteImport } from './routes/protocolo-leonistico'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as LionsInternacionalRouteImport } from './routes/lions-internacional'
import { Route as LcifRouteImport } from './routes/lcif'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as GovernadorRouteImport } from './routes/governador'
import { Route as GatRouteImport } from './routes/gat'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as DoarRouteImport } from './routes/doar'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ClubesRouteImport } from './routes/clubes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssessoriaRouteImport } from './routes/assessoria'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExGovernadoresIndexRouteImport } from './routes/ex-governadores.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ExGovernadoresIdRouteImport } from './routes/ex-governadores.$id'
import { Route as ClubesRjRouteImport } from './routes/clubes.rj'
import { Route as ClubesRegiaoRouteImport } from './routes/clubes.regiao'
import { Route as ClubesEsRouteImport } from './routes/clubes.es'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminRegioesIndexRouteImport } from './routes/admin.regioes.index'
import { Route as AdminProjetosIndexRouteImport } from './routes/admin.projetos.index'
import { Route as AdminPopupsIndexRouteImport } from './routes/admin.popups.index'
import { Route as AdminNoticiasIndexRouteImport } from './routes/admin.noticias.index'
import { Route as AdminLideresIndexRouteImport } from './routes/admin.lideres.index'
import { Route as AdminEventosIndexRouteImport } from './routes/admin.eventos.index'
import { Route as AdminConteudoIndexRouteImport } from './routes/admin.conteudo.index'
import { Route as ProjetosCausaSlugRouteImport } from './routes/projetos.causa.$slug'
import { Route as ClubesRegiaoLetraRouteImport } from './routes/clubes.regiao.$letra'
import { Route as ApiPublicProjetosRouteImport } from './routes/api.public.projetos'
import { Route as ApiPublicLcifRouteImport } from './routes/api.public.lcif'
import { Route as ApiPublicGovernadoresRouteImport } from './routes/api.public.governadores'
import { Route as ApiPublicEventosRouteImport } from './routes/api.public.eventos'
import { Route as AdminRegioesIdRouteImport } from './routes/admin.regioes.$id'
import { Route as AdminProjetosIdRouteImport } from './routes/admin.projetos.$id'
import { Route as AdminPopupsIdRouteImport } from './routes/admin.popups.$id'
import { Route as AdminNoticiasIdRouteImport } from './routes/admin.noticias.$id'
import { Route as AdminLideresIdRouteImport } from './routes/admin.lideres.$id'
import { Route as AdminEventosIdRouteImport } from './routes/admin.eventos.$id'
import { Route as AdminConteudoKeyRouteImport } from './routes/admin.conteudo.$key'
import { Route as AdminRegioesIdDivisoesDivIdRouteImport } from './routes/admin.regioes.$id.divisoes.$divId'
import { Route as AdminRegioesIdDivisoesDivIdClubesClubIdRouteImport } from './routes/admin.regioes.$id.divisoes.$divId.clubes.$clubId'

const ViceGovernador2Route = ViceGovernador2RouteImport.update({
  id: '/vice-governador-2',
  path: '/vice-governador-2',
  getParentRoute: () => rootRouteImport,
} as any)
const ViceGovernador1Route = ViceGovernador1RouteImport.update({
  id: '/vice-governador-1',
  path: '/vice-governador-1',
  getParentRoute: () => rootRouteImport,
} as any)
const TesoureiroRoute = TesoureiroRouteImport.update({
  id: '/tesoureiro',
  path: '/tesoureiro',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretarioRoute = SecretarioRouteImport.update({
  id: '/secretario',
  path: '/secretario',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocoloLeonisticoRoute = ProtocoloLeonisticoRouteImport.update({
  id: '/protocolo-leonistico',
  path: '/protocolo-leonistico',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const LionsInternacionalRoute = LionsInternacionalRouteImport.update({
  id: '/lions-internacional',
  path: '/lions-internacional',
  getParentRoute: () => rootRouteImport,
} as any)
const LcifRoute = LcifRouteImport.update({
  id: '/lcif',
  path: '/lcif',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernadorRoute = GovernadorRouteImport.update({
  id: '/governador',
  path: '/governador',
  getParentRoute: () => rootRouteImport,
} as any)
const GatRoute = GatRouteImport.update({
  id: '/gat',
  path: '/gat',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const DoarRoute = DoarRouteImport.update({
  id: '/doar',
  path: '/doar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubesRoute = ClubesRouteImport.update({
  id: '/clubes',
  path: '/clubes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessoriaRoute = AssessoriaRouteImport.update({
  id: '/assessoria',
  path: '/assessoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExGovernadoresIndexRoute = ExGovernadoresIndexRouteImport.update({
  id: '/ex-governadores/',
  path: '/ex-governadores/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ExGovernadoresIdRoute = ExGovernadoresIdRouteImport.update({
  id: '/ex-governadores/$id',
  path: '/ex-governadores/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubesRjRoute = ClubesRjRouteImport.update({
  id: '/rj',
  path: '/rj',
  getParentRoute: () => ClubesRoute,
} as any)
const ClubesRegiaoRoute = ClubesRegiaoRouteImport.update({
  id: '/regiao',
  path: '/regiao',
  getParentRoute: () => ClubesRoute,
} as any)
const ClubesEsRoute = ClubesEsRouteImport.update({
  id: '/es',
  path: '/es',
  getParentRoute: () => ClubesRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegioesIndexRoute = AdminRegioesIndexRouteImport.update({
  id: '/regioes/',
  path: '/regioes/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjetosIndexRoute = AdminProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPopupsIndexRoute = AdminPopupsIndexRouteImport.update({
  id: '/popups/',
  path: '/popups/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNoticiasIndexRoute = AdminNoticiasIndexRouteImport.update({
  id: '/noticias/',
  path: '/noticias/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLideresIndexRoute = AdminLideresIndexRouteImport.update({
  id: '/lideres/',
  path: '/lideres/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventosIndexRoute = AdminEventosIndexRouteImport.update({
  id: '/eventos/',
  path: '/eventos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConteudoIndexRoute = AdminConteudoIndexRouteImport.update({
  id: '/conteudo/',
  path: '/conteudo/',
  getParentRoute: () => AdminRoute,
} as any)
const ProjetosCausaSlugRoute = ProjetosCausaSlugRouteImport.update({
  id: '/causa/$slug',
  path: '/causa/$slug',
  getParentRoute: () => ProjetosRoute,
} as any)
const ClubesRegiaoLetraRoute = ClubesRegiaoLetraRouteImport.update({
  id: '/$letra',
  path: '/$letra',
  getParentRoute: () => ClubesRegiaoRoute,
} as any)
const ApiPublicProjetosRoute = ApiPublicProjetosRouteImport.update({
  id: '/api/public/projetos',
  path: '/api/public/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLcifRoute = ApiPublicLcifRouteImport.update({
  id: '/api/public/lcif',
  path: '/api/public/lcif',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGovernadoresRoute = ApiPublicGovernadoresRouteImport.update({
  id: '/api/public/governadores',
  path: '/api/public/governadores',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEventosRoute = ApiPublicEventosRouteImport.update({
  id: '/api/public/eventos',
  path: '/api/public/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRegioesIdRoute = AdminRegioesIdRouteImport.update({
  id: '/regioes/$id',
  path: '/regioes/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjetosIdRoute = AdminProjetosIdRouteImport.update({
  id: '/projetos/$id',
  path: '/projetos/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPopupsIdRoute = AdminPopupsIdRouteImport.update({
  id: '/popups/$id',
  path: '/popups/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNoticiasIdRoute = AdminNoticiasIdRouteImport.update({
  id: '/noticias/$id',
  path: '/noticias/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLideresIdRoute = AdminLideresIdRouteImport.update({
  id: '/lideres/$id',
  path: '/lideres/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventosIdRoute = AdminEventosIdRouteImport.update({
  id: '/eventos/$id',
  path: '/eventos/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConteudoKeyRoute = AdminConteudoKeyRouteImport.update({
  id: '/conteudo/$key',
  path: '/conteudo/$key',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegioesIdDivisoesDivIdRoute =
  AdminRegioesIdDivisoesDivIdRouteImport.update({
    id: '/divisoes/$divId',
    path: '/divisoes/$divId',
    getParentRoute: () => AdminRegioesIdRoute,
  } as any)
const AdminRegioesIdDivisoesDivIdClubesClubIdRoute =
  AdminRegioesIdDivisoesDivIdClubesClubIdRouteImport.update({
    id: '/clubes/$clubId',
    path: '/clubes/$clubId',
    getParentRoute: () => AdminRegioesIdDivisoesDivIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assessoria': typeof AssessoriaRoute
  '/auth': typeof AuthRoute
  '/clubes': typeof ClubesRouteWithChildren
  '/contato': typeof ContatoRoute
  '/doar': typeof DoarRoute
  '/eventos': typeof EventosRoute
  '/gat': typeof GatRoute
  '/governador': typeof GovernadorRoute
  '/historia': typeof HistoriaRoute
  '/lcif': typeof LcifRoute
  '/lions-internacional': typeof LionsInternacionalRoute
  '/noticias': typeof NoticiasRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/protocolo-leonistico': typeof ProtocoloLeonisticoRoute
  '/secretario': typeof SecretarioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/tesoureiro': typeof TesoureiroRoute
  '/vice-governador-1': typeof ViceGovernador1Route
  '/vice-governador-2': typeof ViceGovernador2Route
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/clubes/es': typeof ClubesEsRoute
  '/clubes/regiao': typeof ClubesRegiaoRouteWithChildren
  '/clubes/rj': typeof ClubesRjRoute
  '/ex-governadores/$id': typeof ExGovernadoresIdRoute
  '/admin/': typeof AdminIndexRoute
  '/ex-governadores/': typeof ExGovernadoresIndexRoute
  '/admin/conteudo/$key': typeof AdminConteudoKeyRoute
  '/admin/eventos/$id': typeof AdminEventosIdRoute
  '/admin/lideres/$id': typeof AdminLideresIdRoute
  '/admin/noticias/$id': typeof AdminNoticiasIdRoute
  '/admin/popups/$id': typeof AdminPopupsIdRoute
  '/admin/projetos/$id': typeof AdminProjetosIdRoute
  '/admin/regioes/$id': typeof AdminRegioesIdRouteWithChildren
  '/api/public/eventos': typeof ApiPublicEventosRoute
  '/api/public/governadores': typeof ApiPublicGovernadoresRoute
  '/api/public/lcif': typeof ApiPublicLcifRoute
  '/api/public/projetos': typeof ApiPublicProjetosRoute
  '/clubes/regiao/$letra': typeof ClubesRegiaoLetraRoute
  '/projetos/causa/$slug': typeof ProjetosCausaSlugRoute
  '/admin/conteudo/': typeof AdminConteudoIndexRoute
  '/admin/eventos/': typeof AdminEventosIndexRoute
  '/admin/lideres/': typeof AdminLideresIndexRoute
  '/admin/noticias/': typeof AdminNoticiasIndexRoute
  '/admin/popups/': typeof AdminPopupsIndexRoute
  '/admin/projetos/': typeof AdminProjetosIndexRoute
  '/admin/regioes/': typeof AdminRegioesIndexRoute
  '/admin/regioes/$id/divisoes/$divId': typeof AdminRegioesIdDivisoesDivIdRouteWithChildren
  '/admin/regioes/$id/divisoes/$divId/clubes/$clubId': typeof AdminRegioesIdDivisoesDivIdClubesClubIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessoria': typeof AssessoriaRoute
  '/auth': typeof AuthRoute
  '/clubes': typeof ClubesRouteWithChildren
  '/contato': typeof ContatoRoute
  '/doar': typeof DoarRoute
  '/eventos': typeof EventosRoute
  '/gat': typeof GatRoute
  '/governador': typeof GovernadorRoute
  '/historia': typeof HistoriaRoute
  '/lcif': typeof LcifRoute
  '/lions-internacional': typeof LionsInternacionalRoute
  '/noticias': typeof NoticiasRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/protocolo-leonistico': typeof ProtocoloLeonisticoRoute
  '/secretario': typeof SecretarioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/tesoureiro': typeof TesoureiroRoute
  '/vice-governador-1': typeof ViceGovernador1Route
  '/vice-governador-2': typeof ViceGovernador2Route
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/clubes/es': typeof ClubesEsRoute
  '/clubes/regiao': typeof ClubesRegiaoRouteWithChildren
  '/clubes/rj': typeof ClubesRjRoute
  '/ex-governadores/$id': typeof ExGovernadoresIdRoute
  '/admin': typeof AdminIndexRoute
  '/ex-governadores': typeof ExGovernadoresIndexRoute
  '/admin/conteudo/$key': typeof AdminConteudoKeyRoute
  '/admin/eventos/$id': typeof AdminEventosIdRoute
  '/admin/lideres/$id': typeof AdminLideresIdRoute
  '/admin/noticias/$id': typeof AdminNoticiasIdRoute
  '/admin/popups/$id': typeof AdminPopupsIdRoute
  '/admin/projetos/$id': typeof AdminProjetosIdRoute
  '/admin/regioes/$id': typeof AdminRegioesIdRouteWithChildren
  '/api/public/eventos': typeof ApiPublicEventosRoute
  '/api/public/governadores': typeof ApiPublicGovernadoresRoute
  '/api/public/lcif': typeof ApiPublicLcifRoute
  '/api/public/projetos': typeof ApiPublicProjetosRoute
  '/clubes/regiao/$letra': typeof ClubesRegiaoLetraRoute
  '/projetos/causa/$slug': typeof ProjetosCausaSlugRoute
  '/admin/conteudo': typeof AdminConteudoIndexRoute
  '/admin/eventos': typeof AdminEventosIndexRoute
  '/admin/lideres': typeof AdminLideresIndexRoute
  '/admin/noticias': typeof AdminNoticiasIndexRoute
  '/admin/popups': typeof AdminPopupsIndexRoute
  '/admin/projetos': typeof AdminProjetosIndexRoute
  '/admin/regioes': typeof AdminRegioesIndexRoute
  '/admin/regioes/$id/divisoes/$divId': typeof AdminRegioesIdDivisoesDivIdRouteWithChildren
  '/admin/regioes/$id/divisoes/$divId/clubes/$clubId': typeof AdminRegioesIdDivisoesDivIdClubesClubIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assessoria': typeof AssessoriaRoute
  '/auth': typeof AuthRoute
  '/clubes': typeof ClubesRouteWithChildren
  '/contato': typeof ContatoRoute
  '/doar': typeof DoarRoute
  '/eventos': typeof EventosRoute
  '/gat': typeof GatRoute
  '/governador': typeof GovernadorRoute
  '/historia': typeof HistoriaRoute
  '/lcif': typeof LcifRoute
  '/lions-internacional': typeof LionsInternacionalRoute
  '/noticias': typeof NoticiasRoute
  '/projetos': typeof ProjetosRouteWithChildren
  '/protocolo-leonistico': typeof ProtocoloLeonisticoRoute
  '/secretario': typeof SecretarioRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/tesoureiro': typeof TesoureiroRoute
  '/vice-governador-1': typeof ViceGovernador1Route
  '/vice-governador-2': typeof ViceGovernador2Route
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/clubes/es': typeof ClubesEsRoute
  '/clubes/regiao': typeof ClubesRegiaoRouteWithChildren
  '/clubes/rj': typeof ClubesRjRoute
  '/ex-governadores/$id': typeof ExGovernadoresIdRoute
  '/admin/': typeof AdminIndexRoute
  '/ex-governadores/': typeof ExGovernadoresIndexRoute
  '/admin/conteudo/$key': typeof AdminConteudoKeyRoute
  '/admin/eventos/$id': typeof AdminEventosIdRoute
  '/admin/lideres/$id': typeof AdminLideresIdRoute
  '/admin/noticias/$id': typeof AdminNoticiasIdRoute
  '/admin/popups/$id': typeof AdminPopupsIdRoute
  '/admin/projetos/$id': typeof AdminProjetosIdRoute
  '/admin/regioes/$id': typeof AdminRegioesIdRouteWithChildren
  '/api/public/eventos': typeof ApiPublicEventosRoute
  '/api/public/governadores': typeof ApiPublicGovernadoresRoute
  '/api/public/lcif': typeof ApiPublicLcifRoute
  '/api/public/projetos': typeof ApiPublicProjetosRoute
  '/clubes/regiao/$letra': typeof ClubesRegiaoLetraRoute
  '/projetos/causa/$slug': typeof ProjetosCausaSlugRoute
  '/admin/conteudo/': typeof AdminConteudoIndexRoute
  '/admin/eventos/': typeof AdminEventosIndexRoute
  '/admin/lideres/': typeof AdminLideresIndexRoute
  '/admin/noticias/': typeof AdminNoticiasIndexRoute
  '/admin/popups/': typeof AdminPopupsIndexRoute
  '/admin/projetos/': typeof AdminProjetosIndexRoute
  '/admin/regioes/': typeof AdminRegioesIndexRoute
  '/admin/regioes/$id/divisoes/$divId': typeof AdminRegioesIdDivisoesDivIdRouteWithChildren
  '/admin/regioes/$id/divisoes/$divId/clubes/$clubId': typeof AdminRegioesIdDivisoesDivIdClubesClubIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assessoria'
    | '/auth'
    | '/clubes'
    | '/contato'
    | '/doar'
    | '/eventos'
    | '/gat'
    | '/governador'
    | '/historia'
    | '/lcif'
    | '/lions-internacional'
    | '/noticias'
    | '/projetos'
    | '/protocolo-leonistico'
    | '/secretario'
    | '/sitemap.xml'
    | '/sobre'
    | '/tesoureiro'
    | '/vice-governador-1'
    | '/vice-governador-2'
    | '/admin/usuarios'
    | '/clubes/es'
    | '/clubes/regiao'
    | '/clubes/rj'
    | '/ex-governadores/$id'
    | '/admin/'
    | '/ex-governadores/'
    | '/admin/conteudo/$key'
    | '/admin/eventos/$id'
    | '/admin/lideres/$id'
    | '/admin/noticias/$id'
    | '/admin/popups/$id'
    | '/admin/projetos/$id'
    | '/admin/regioes/$id'
    | '/api/public/eventos'
    | '/api/public/governadores'
    | '/api/public/lcif'
    | '/api/public/projetos'
    | '/clubes/regiao/$letra'
    | '/projetos/causa/$slug'
    | '/admin/conteudo/'
    | '/admin/eventos/'
    | '/admin/lideres/'
    | '/admin/noticias/'
    | '/admin/popups/'
    | '/admin/projetos/'
    | '/admin/regioes/'
    | '/admin/regioes/$id/divisoes/$divId'
    | '/admin/regioes/$id/divisoes/$divId/clubes/$clubId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessoria'
    | '/auth'
    | '/clubes'
    | '/contato'
    | '/doar'
    | '/eventos'
    | '/gat'
    | '/governador'
    | '/historia'
    | '/lcif'
    | '/lions-internacional'
    | '/noticias'
    | '/projetos'
    | '/protocolo-leonistico'
    | '/secretario'
    | '/sitemap.xml'
    | '/sobre'
    | '/tesoureiro'
    | '/vice-governador-1'
    | '/vice-governador-2'
    | '/admin/usuarios'
    | '/clubes/es'
    | '/clubes/regiao'
    | '/clubes/rj'
    | '/ex-governadores/$id'
    | '/admin'
    | '/ex-governadores'
    | '/admin/conteudo/$key'
    | '/admin/eventos/$id'
    | '/admin/lideres/$id'
    | '/admin/noticias/$id'
    | '/admin/popups/$id'
    | '/admin/projetos/$id'
    | '/admin/regioes/$id'
    | '/api/public/eventos'
    | '/api/public/governadores'
    | '/api/public/lcif'
    | '/api/public/projetos'
    | '/clubes/regiao/$letra'
    | '/projetos/causa/$slug'
    | '/admin/conteudo'
    | '/admin/eventos'
    | '/admin/lideres'
    | '/admin/noticias'
    | '/admin/popups'
    | '/admin/projetos'
    | '/admin/regioes'
    | '/admin/regioes/$id/divisoes/$divId'
    | '/admin/regioes/$id/divisoes/$divId/clubes/$clubId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assessoria'
    | '/auth'
    | '/clubes'
    | '/contato'
    | '/doar'
    | '/eventos'
    | '/gat'
    | '/governador'
    | '/historia'
    | '/lcif'
    | '/lions-internacional'
    | '/noticias'
    | '/projetos'
    | '/protocolo-leonistico'
    | '/secretario'
    | '/sitemap.xml'
    | '/sobre'
    | '/tesoureiro'
    | '/vice-governador-1'
    | '/vice-governador-2'
    | '/admin/usuarios'
    | '/clubes/es'
    | '/clubes/regiao'
    | '/clubes/rj'
    | '/ex-governadores/$id'
    | '/admin/'
    | '/ex-governadores/'
    | '/admin/conteudo/$key'
    | '/admin/eventos/$id'
    | '/admin/lideres/$id'
    | '/admin/noticias/$id'
    | '/admin/popups/$id'
    | '/admin/projetos/$id'
    | '/admin/regioes/$id'
    | '/api/public/eventos'
    | '/api/public/governadores'
    | '/api/public/lcif'
    | '/api/public/projetos'
    | '/clubes/regiao/$letra'
    | '/projetos/causa/$slug'
    | '/admin/conteudo/'
    | '/admin/eventos/'
    | '/admin/lideres/'
    | '/admin/noticias/'
    | '/admin/popups/'
    | '/admin/projetos/'
    | '/admin/regioes/'
    | '/admin/regioes/$id/divisoes/$divId'
    | '/admin/regioes/$id/divisoes/$divId/clubes/$clubId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AssessoriaRoute: typeof AssessoriaRoute
  AuthRoute: typeof AuthRoute
  ClubesRoute: typeof ClubesRouteWithChildren
  ContatoRoute: typeof ContatoRoute
  DoarRoute: typeof DoarRoute
  EventosRoute: typeof EventosRoute
  GatRoute: typeof GatRoute
  GovernadorRoute: typeof GovernadorRoute
  HistoriaRoute: typeof HistoriaRoute
  LcifRoute: typeof LcifRoute
  LionsInternacionalRoute: typeof LionsInternacionalRoute
  NoticiasRoute: typeof NoticiasRoute
  ProjetosRoute: typeof ProjetosRouteWithChildren
  ProtocoloLeonisticoRoute: typeof ProtocoloLeonisticoRoute
  SecretarioRoute: typeof SecretarioRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  TesoureiroRoute: typeof TesoureiroRoute
  ViceGovernador1Route: typeof ViceGovernador1Route
  ViceGovernador2Route: typeof ViceGovernador2Route
  ExGovernadoresIdRoute: typeof ExGovernadoresIdRoute
  ExGovernadoresIndexRoute: typeof ExGovernadoresIndexRoute
  ApiPublicEventosRoute: typeof ApiPublicEventosRoute
  ApiPublicGovernadoresRoute: typeof ApiPublicGovernadoresRoute
  ApiPublicLcifRoute: typeof ApiPublicLcifRoute
  ApiPublicProjetosRoute: typeof ApiPublicProjetosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vice-governador-2': {
      id: '/vice-governador-2'
      path: '/vice-governador-2'
      fullPath: '/vice-governador-2'
      preLoaderRoute: typeof ViceGovernador2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vice-governador-1': {
      id: '/vice-governador-1'
      path: '/vice-governador-1'
      fullPath: '/vice-governador-1'
      preLoaderRoute: typeof ViceGovernador1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tesoureiro': {
      id: '/tesoureiro'
      path: '/tesoureiro'
      fullPath: '/tesoureiro'
      preLoaderRoute: typeof TesoureiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secretario': {
      id: '/secretario'
      path: '/secretario'
      fullPath: '/secretario'
      preLoaderRoute: typeof SecretarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocolo-leonistico': {
      id: '/protocolo-leonistico'
      path: '/protocolo-leonistico'
      fullPath: '/protocolo-leonistico'
      preLoaderRoute: typeof ProtocoloLeonisticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lions-internacional': {
      id: '/lions-internacional'
      path: '/lions-internacional'
      fullPath: '/lions-internacional'
      preLoaderRoute: typeof LionsInternacionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lcif': {
      id: '/lcif'
      path: '/lcif'
      fullPath: '/lcif'
      preLoaderRoute: typeof LcifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governador': {
      id: '/governador'
      path: '/governador'
      fullPath: '/governador'
      preLoaderRoute: typeof GovernadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gat': {
      id: '/gat'
      path: '/gat'
      fullPath: '/gat'
      preLoaderRoute: typeof GatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doar': {
      id: '/doar'
      path: '/doar'
      fullPath: '/doar'
      preLoaderRoute: typeof DoarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubes': {
      id: '/clubes'
      path: '/clubes'
      fullPath: '/clubes'
      preLoaderRoute: typeof ClubesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessoria': {
      id: '/assessoria'
      path: '/assessoria'
      fullPath: '/assessoria'
      preLoaderRoute: typeof AssessoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ex-governadores/': {
      id: '/ex-governadores/'
      path: '/ex-governadores'
      fullPath: '/ex-governadores/'
      preLoaderRoute: typeof ExGovernadoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/ex-governadores/$id': {
      id: '/ex-governadores/$id'
      path: '/ex-governadores/$id'
      fullPath: '/ex-governadores/$id'
      preLoaderRoute: typeof ExGovernadoresIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubes/rj': {
      id: '/clubes/rj'
      path: '/rj'
      fullPath: '/clubes/rj'
      preLoaderRoute: typeof ClubesRjRouteImport
      parentRoute: typeof ClubesRoute
    }
    '/clubes/regiao': {
      id: '/clubes/regiao'
      path: '/regiao'
      fullPath: '/clubes/regiao'
      preLoaderRoute: typeof ClubesRegiaoRouteImport
      parentRoute: typeof ClubesRoute
    }
    '/clubes/es': {
      id: '/clubes/es'
      path: '/es'
      fullPath: '/clubes/es'
      preLoaderRoute: typeof ClubesEsRouteImport
      parentRoute: typeof ClubesRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/regioes/': {
      id: '/admin/regioes/'
      path: '/regioes'
      fullPath: '/admin/regioes/'
      preLoaderRoute: typeof AdminRegioesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projetos/': {
      id: '/admin/projetos/'
      path: '/projetos'
      fullPath: '/admin/projetos/'
      preLoaderRoute: typeof AdminProjetosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/popups/': {
      id: '/admin/popups/'
      path: '/popups'
      fullPath: '/admin/popups/'
      preLoaderRoute: typeof AdminPopupsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/noticias/': {
      id: '/admin/noticias/'
      path: '/noticias'
      fullPath: '/admin/noticias/'
      preLoaderRoute: typeof AdminNoticiasIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lideres/': {
      id: '/admin/lideres/'
      path: '/lideres'
      fullPath: '/admin/lideres/'
      preLoaderRoute: typeof AdminLideresIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eventos/': {
      id: '/admin/eventos/'
      path: '/eventos'
      fullPath: '/admin/eventos/'
      preLoaderRoute: typeof AdminEventosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conteudo/': {
      id: '/admin/conteudo/'
      path: '/conteudo'
      fullPath: '/admin/conteudo/'
      preLoaderRoute: typeof AdminConteudoIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/projetos/causa/$slug': {
      id: '/projetos/causa/$slug'
      path: '/causa/$slug'
      fullPath: '/projetos/causa/$slug'
      preLoaderRoute: typeof ProjetosCausaSlugRouteImport
      parentRoute: typeof ProjetosRoute
    }
    '/clubes/regiao/$letra': {
      id: '/clubes/regiao/$letra'
      path: '/$letra'
      fullPath: '/clubes/regiao/$letra'
      preLoaderRoute: typeof ClubesRegiaoLetraRouteImport
      parentRoute: typeof ClubesRegiaoRoute
    }
    '/api/public/projetos': {
      id: '/api/public/projetos'
      path: '/api/public/projetos'
      fullPath: '/api/public/projetos'
      preLoaderRoute: typeof ApiPublicProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lcif': {
      id: '/api/public/lcif'
      path: '/api/public/lcif'
      fullPath: '/api/public/lcif'
      preLoaderRoute: typeof ApiPublicLcifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/governadores': {
      id: '/api/public/governadores'
      path: '/api/public/governadores'
      fullPath: '/api/public/governadores'
      preLoaderRoute: typeof ApiPublicGovernadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/eventos': {
      id: '/api/public/eventos'
      path: '/api/public/eventos'
      fullPath: '/api/public/eventos'
      preLoaderRoute: typeof ApiPublicEventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/regioes/$id': {
      id: '/admin/regioes/$id'
      path: '/regioes/$id'
      fullPath: '/admin/regioes/$id'
      preLoaderRoute: typeof AdminRegioesIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projetos/$id': {
      id: '/admin/projetos/$id'
      path: '/projetos/$id'
      fullPath: '/admin/projetos/$id'
      preLoaderRoute: typeof AdminProjetosIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/popups/$id': {
      id: '/admin/popups/$id'
      path: '/popups/$id'
      fullPath: '/admin/popups/$id'
      preLoaderRoute: typeof AdminPopupsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/noticias/$id': {
      id: '/admin/noticias/$id'
      path: '/noticias/$id'
      fullPath: '/admin/noticias/$id'
      preLoaderRoute: typeof AdminNoticiasIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lideres/$id': {
      id: '/admin/lideres/$id'
      path: '/lideres/$id'
      fullPath: '/admin/lideres/$id'
      preLoaderRoute: typeof AdminLideresIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eventos/$id': {
      id: '/admin/eventos/$id'
      path: '/eventos/$id'
      fullPath: '/admin/eventos/$id'
      preLoaderRoute: typeof AdminEventosIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conteudo/$key': {
      id: '/admin/conteudo/$key'
      path: '/conteudo/$key'
      fullPath: '/admin/conteudo/$key'
      preLoaderRoute: typeof AdminConteudoKeyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/regioes/$id/divisoes/$divId': {
      id: '/admin/regioes/$id/divisoes/$divId'
      path: '/divisoes/$divId'
      fullPath: '/admin/regioes/$id/divisoes/$divId'
      preLoaderRoute: typeof AdminRegioesIdDivisoesDivIdRouteImport
      parentRoute: typeof AdminRegioesIdRoute
    }
    '/admin/regioes/$id/divisoes/$divId/clubes/$clubId': {
      id: '/admin/regioes/$id/divisoes/$divId/clubes/$clubId'
      path: '/clubes/$clubId'
      fullPath: '/admin/regioes/$id/divisoes/$divId/clubes/$clubId'
      preLoaderRoute: typeof AdminRegioesIdDivisoesDivIdClubesClubIdRouteImport
      parentRoute: typeof AdminRegioesIdDivisoesDivIdRoute
    }
  }
}

interface AdminRegioesIdDivisoesDivIdRouteChildren {
  AdminRegioesIdDivisoesDivIdClubesClubIdRoute: typeof AdminRegioesIdDivisoesDivIdClubesClubIdRoute
}

const AdminRegioesIdDivisoesDivIdRouteChildren: AdminRegioesIdDivisoesDivIdRouteChildren =
  {
    AdminRegioesIdDivisoesDivIdClubesClubIdRoute:
      AdminRegioesIdDivisoesDivIdClubesClubIdRoute,
  }

const AdminRegioesIdDivisoesDivIdRouteWithChildren =
  AdminRegioesIdDivisoesDivIdRoute._addFileChildren(
    AdminRegioesIdDivisoesDivIdRouteChildren,
  )

interface AdminRegioesIdRouteChildren {
  AdminRegioesIdDivisoesDivIdRoute: typeof AdminRegioesIdDivisoesDivIdRouteWithChildren
}

const AdminRegioesIdRouteChildren: AdminRegioesIdRouteChildren = {
  AdminRegioesIdDivisoesDivIdRoute:
    AdminRegioesIdDivisoesDivIdRouteWithChildren,
}

const AdminRegioesIdRouteWithChildren = AdminRegioesIdRoute._addFileChildren(
  AdminRegioesIdRouteChildren,
)

interface AdminRouteChildren {
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminConteudoKeyRoute: typeof AdminConteudoKeyRoute
  AdminEventosIdRoute: typeof AdminEventosIdRoute
  AdminLideresIdRoute: typeof AdminLideresIdRoute
  AdminNoticiasIdRoute: typeof AdminNoticiasIdRoute
  AdminPopupsIdRoute: typeof AdminPopupsIdRoute
  AdminProjetosIdRoute: typeof AdminProjetosIdRoute
  AdminRegioesIdRoute: typeof AdminRegioesIdRouteWithChildren
  AdminConteudoIndexRoute: typeof AdminConteudoIndexRoute
  AdminEventosIndexRoute: typeof AdminEventosIndexRoute
  AdminLideresIndexRoute: typeof AdminLideresIndexRoute
  AdminNoticiasIndexRoute: typeof AdminNoticiasIndexRoute
  AdminPopupsIndexRoute: typeof AdminPopupsIndexRoute
  AdminProjetosIndexRoute: typeof AdminProjetosIndexRoute
  AdminRegioesIndexRoute: typeof AdminRegioesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminConteudoKeyRoute: AdminConteudoKeyRoute,
  AdminEventosIdRoute: AdminEventosIdRoute,
  AdminLideresIdRoute: AdminLideresIdRoute,
  AdminNoticiasIdRoute: AdminNoticiasIdRoute,
  AdminPopupsIdRoute: AdminPopupsIdRoute,
  AdminProjetosIdRoute: AdminProjetosIdRoute,
  AdminRegioesIdRoute: AdminRegioesIdRouteWithChildren,
  AdminConteudoIndexRoute: AdminConteudoIndexRoute,
  AdminEventosIndexRoute: AdminEventosIndexRoute,
  AdminLideresIndexRoute: AdminLideresIndexRoute,
  AdminNoticiasIndexRoute: AdminNoticiasIndexRoute,
  AdminPopupsIndexRoute: AdminPopupsIndexRoute,
  AdminProjetosIndexRoute: AdminProjetosIndexRoute,
  AdminRegioesIndexRoute: AdminRegioesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClubesRegiaoRouteChildren {
  ClubesRegiaoLetraRoute: typeof ClubesRegiaoLetraRoute
}

const ClubesRegiaoRouteChildren: ClubesRegiaoRouteChildren = {
  ClubesRegiaoLetraRoute: ClubesRegiaoLetraRoute,
}

const ClubesRegiaoRouteWithChildren = ClubesRegiaoRoute._addFileChildren(
  ClubesRegiaoRouteChildren,
)

interface ClubesRouteChildren {
  ClubesEsRoute: typeof ClubesEsRoute
  ClubesRegiaoRoute: typeof ClubesRegiaoRouteWithChildren
  ClubesRjRoute: typeof ClubesRjRoute
}

const ClubesRouteChildren: ClubesRouteChildren = {
  ClubesEsRoute: ClubesEsRoute,
  ClubesRegiaoRoute: ClubesRegiaoRouteWithChildren,
  ClubesRjRoute: ClubesRjRoute,
}

const ClubesRouteWithChildren =
  ClubesRoute._addFileChildren(ClubesRouteChildren)

interface ProjetosRouteChildren {
  ProjetosCausaSlugRoute: typeof ProjetosCausaSlugRoute
}

const ProjetosRouteChildren: ProjetosRouteChildren = {
  ProjetosCausaSlugRoute: ProjetosCausaSlugRoute,
}

const ProjetosRouteWithChildren = ProjetosRoute._addFileChildren(
  ProjetosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AssessoriaRoute: AssessoriaRoute,
  AuthRoute: AuthRoute,
  ClubesRoute: ClubesRouteWithChildren,
  ContatoRoute: ContatoRoute,
  DoarRoute: DoarRoute,
  EventosRoute: EventosRoute,
  GatRoute: GatRoute,
  GovernadorRoute: GovernadorRoute,
  HistoriaRoute: HistoriaRoute,
  LcifRoute: LcifRoute,
  LionsInternacionalRoute: LionsInternacionalRoute,
  NoticiasRoute: NoticiasRoute,
  ProjetosRoute: ProjetosRouteWithChildren,
  ProtocoloLeonisticoRoute: ProtocoloLeonisticoRoute,
  SecretarioRoute: SecretarioRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  TesoureiroRoute: TesoureiroRoute,
  ViceGovernador1Route: ViceGovernador1Route,
  ViceGovernador2Route: ViceGovernador2Route,
  ExGovernadoresIdRoute: ExGovernadoresIdRoute,
  ExGovernadoresIndexRoute: ExGovernadoresIndexRoute,
  ApiPublicEventosRoute: ApiPublicEventosRoute,
  ApiPublicGovernadoresRoute: ApiPublicGovernadoresRoute,
  ApiPublicLcifRoute: ApiPublicLcifRoute,
  ApiPublicProjetosRoute: ApiPublicProjetosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
