/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViceGovernador2RouteImport } from './routes/vice-governador-2'
import { Route as ViceGovernador1RouteImport } from './routes/vice-governador-1'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as LionsInternacionalRouteImport } from './routes/lions-internacional'
import { Route as LcifRouteImport } from './routes/lcif'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as GovernadorRouteImport } from './routes/governador'
import { Route as GatRouteImport } from './routes/gat'
import { Route as ExGovernadoresRouteImport } from './routes/ex-governadores'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as DoarRouteImport } from './routes/doar'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ClubesRouteImport } from './routes/clubes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssessoriaRouteImport } from './routes/assessoria'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLideresIndexRouteImport } from './routes/admin.lideres.index'
import { Route as AdminConteudoIndexRouteImport } from './routes/admin.conteudo.index'
import { Route as AdminLideresIdRouteImport } from './routes/admin.lideres.$id'
import { Route as AdminConteudoKeyRouteImport } from './routes/admin.conteudo.$key'

const ViceGovernador2Route = ViceGovernador2RouteImport.update({
  id: '/vice-governador-2',
  path: '/vice-governador-2',
  getParentRoute: () => rootRouteImport,
} as any)
const ViceGovernador1Route = ViceGovernador1RouteImport.update({
  id: '/vice-governador-1',
  path: '/vice-governador-1',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const LionsInternacionalRoute = LionsInternacionalRouteImport.update({
  id: '/lions-internacional',
  path: '/lions-internacional',
  getParentRoute: () => rootRouteImport,
} as any)
const LcifRoute = LcifRouteImport.update({
  id: '/lcif',
  path: '/lcif',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernadorRoute = GovernadorRouteImport.update({
  id: '/governador',
  path: '/governador',
  getParentRoute: () => rootRouteImport,
} as any)
const GatRoute = GatRouteImport.update({
  id: '/gat',
  path: '/gat',
  getParentRoute: () => rootRouteImport,
} as any)
const ExGovernadoresRoute = ExGovernadoresRouteImport.update({
  id: '/ex-governadores',
  path: '/ex-governadores',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const DoarRoute = DoarRouteImport.update({
  id: '/doar',
  path: '/doar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubesRoute = ClubesRouteImport.update({
  id: '/clubes',
  path: '/clubes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessoriaRoute = AssessoriaRouteImport.update({
  id: '/assessoria',
  path: '/assessoria',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLideresIndexRoute = AdminLideresIndexRouteImport.update({
  id: '/lideres/',
  path: '/lideres/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConteudoIndexRoute = AdminConteudoIndexRouteImport.update({
  id: '/conteudo/',
  path: '/conteudo/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLideresIdRoute = AdminLideresIdRouteImport.update({
  id: '/lideres/$id',
  path: '/lideres/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConteudoKeyRoute = AdminConteudoKeyRouteImport.update({
  id: '/conteudo/$key',
  path: '/conteudo/$key',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assessoria': typeof AssessoriaRoute
  '/auth': typeof AuthRoute
  '/clubes': typeof ClubesRoute
  '/contato': typeof ContatoRoute
  '/doar': typeof DoarRoute
  '/eventos': typeof EventosRoute
  '/ex-governadores': typeof ExGovernadoresRoute
  '/gat': typeof GatRoute
  '/governador': typeof GovernadorRoute
  '/historia': typeof HistoriaRoute
  '/lcif': typeof LcifRoute
  '/lions-internacional': typeof LionsInternacionalRoute
  '/noticias': typeof NoticiasRoute
  '/projetos': typeof ProjetosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/vice-governador-1': typeof ViceGovernador1Route
  '/vice-governador-2': typeof ViceGovernador2Route
  '/admin/': typeof AdminIndexRoute
  '/admin/conteudo/$key': typeof AdminConteudoKeyRoute
  '/admin/lideres/$id': typeof AdminLideresIdRoute
  '/admin/conteudo/': typeof AdminConteudoIndexRoute
  '/admin/lideres/': typeof AdminLideresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assessoria': typeof AssessoriaRoute
  '/auth': typeof AuthRoute
  '/clubes': typeof ClubesRoute
  '/contato': typeof ContatoRoute
  '/doar': typeof DoarRoute
  '/eventos': typeof EventosRoute
  '/ex-governadores': typeof ExGovernadoresRoute
  '/gat': typeof GatRoute
  '/governador': typeof GovernadorRoute
  '/historia': typeof HistoriaRoute
  '/lcif': typeof LcifRoute
  '/lions-internacional': typeof LionsInternacionalRoute
  '/noticias': typeof NoticiasRoute
  '/projetos': typeof ProjetosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/vice-governador-1': typeof ViceGovernador1Route
  '/vice-governador-2': typeof ViceGovernador2Route
  '/admin': typeof AdminIndexRoute
  '/admin/conteudo/$key': typeof AdminConteudoKeyRoute
  '/admin/lideres/$id': typeof AdminLideresIdRoute
  '/admin/conteudo': typeof AdminConteudoIndexRoute
  '/admin/lideres': typeof AdminLideresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assessoria': typeof AssessoriaRoute
  '/auth': typeof AuthRoute
  '/clubes': typeof ClubesRoute
  '/contato': typeof ContatoRoute
  '/doar': typeof DoarRoute
  '/eventos': typeof EventosRoute
  '/ex-governadores': typeof ExGovernadoresRoute
  '/gat': typeof GatRoute
  '/governador': typeof GovernadorRoute
  '/historia': typeof HistoriaRoute
  '/lcif': typeof LcifRoute
  '/lions-internacional': typeof LionsInternacionalRoute
  '/noticias': typeof NoticiasRoute
  '/projetos': typeof ProjetosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/vice-governador-1': typeof ViceGovernador1Route
  '/vice-governador-2': typeof ViceGovernador2Route
  '/admin/': typeof AdminIndexRoute
  '/admin/conteudo/$key': typeof AdminConteudoKeyRoute
  '/admin/lideres/$id': typeof AdminLideresIdRoute
  '/admin/conteudo/': typeof AdminConteudoIndexRoute
  '/admin/lideres/': typeof AdminLideresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assessoria'
    | '/auth'
    | '/clubes'
    | '/contato'
    | '/doar'
    | '/eventos'
    | '/ex-governadores'
    | '/gat'
    | '/governador'
    | '/historia'
    | '/lcif'
    | '/lions-internacional'
    | '/noticias'
    | '/projetos'
    | '/sitemap.xml'
    | '/sobre'
    | '/vice-governador-1'
    | '/vice-governador-2'
    | '/admin/'
    | '/admin/conteudo/$key'
    | '/admin/lideres/$id'
    | '/admin/conteudo/'
    | '/admin/lideres/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assessoria'
    | '/auth'
    | '/clubes'
    | '/contato'
    | '/doar'
    | '/eventos'
    | '/ex-governadores'
    | '/gat'
    | '/governador'
    | '/historia'
    | '/lcif'
    | '/lions-internacional'
    | '/noticias'
    | '/projetos'
    | '/sitemap.xml'
    | '/sobre'
    | '/vice-governador-1'
    | '/vice-governador-2'
    | '/admin'
    | '/admin/conteudo/$key'
    | '/admin/lideres/$id'
    | '/admin/conteudo'
    | '/admin/lideres'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assessoria'
    | '/auth'
    | '/clubes'
    | '/contato'
    | '/doar'
    | '/eventos'
    | '/ex-governadores'
    | '/gat'
    | '/governador'
    | '/historia'
    | '/lcif'
    | '/lions-internacional'
    | '/noticias'
    | '/projetos'
    | '/sitemap.xml'
    | '/sobre'
    | '/vice-governador-1'
    | '/vice-governador-2'
    | '/admin/'
    | '/admin/conteudo/$key'
    | '/admin/lideres/$id'
    | '/admin/conteudo/'
    | '/admin/lideres/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AssessoriaRoute: typeof AssessoriaRoute
  AuthRoute: typeof AuthRoute
  ClubesRoute: typeof ClubesRoute
  ContatoRoute: typeof ContatoRoute
  DoarRoute: typeof DoarRoute
  EventosRoute: typeof EventosRoute
  ExGovernadoresRoute: typeof ExGovernadoresRoute
  GatRoute: typeof GatRoute
  GovernadorRoute: typeof GovernadorRoute
  HistoriaRoute: typeof HistoriaRoute
  LcifRoute: typeof LcifRoute
  LionsInternacionalRoute: typeof LionsInternacionalRoute
  NoticiasRoute: typeof NoticiasRoute
  ProjetosRoute: typeof ProjetosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  ViceGovernador1Route: typeof ViceGovernador1Route
  ViceGovernador2Route: typeof ViceGovernador2Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vice-governador-2': {
      id: '/vice-governador-2'
      path: '/vice-governador-2'
      fullPath: '/vice-governador-2'
      preLoaderRoute: typeof ViceGovernador2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vice-governador-1': {
      id: '/vice-governador-1'
      path: '/vice-governador-1'
      fullPath: '/vice-governador-1'
      preLoaderRoute: typeof ViceGovernador1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lions-internacional': {
      id: '/lions-internacional'
      path: '/lions-internacional'
      fullPath: '/lions-internacional'
      preLoaderRoute: typeof LionsInternacionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lcif': {
      id: '/lcif'
      path: '/lcif'
      fullPath: '/lcif'
      preLoaderRoute: typeof LcifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governador': {
      id: '/governador'
      path: '/governador'
      fullPath: '/governador'
      preLoaderRoute: typeof GovernadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gat': {
      id: '/gat'
      path: '/gat'
      fullPath: '/gat'
      preLoaderRoute: typeof GatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ex-governadores': {
      id: '/ex-governadores'
      path: '/ex-governadores'
      fullPath: '/ex-governadores'
      preLoaderRoute: typeof ExGovernadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doar': {
      id: '/doar'
      path: '/doar'
      fullPath: '/doar'
      preLoaderRoute: typeof DoarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clubes': {
      id: '/clubes'
      path: '/clubes'
      fullPath: '/clubes'
      preLoaderRoute: typeof ClubesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessoria': {
      id: '/assessoria'
      path: '/assessoria'
      fullPath: '/assessoria'
      preLoaderRoute: typeof AssessoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lideres/': {
      id: '/admin/lideres/'
      path: '/lideres'
      fullPath: '/admin/lideres/'
      preLoaderRoute: typeof AdminLideresIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conteudo/': {
      id: '/admin/conteudo/'
      path: '/conteudo'
      fullPath: '/admin/conteudo/'
      preLoaderRoute: typeof AdminConteudoIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lideres/$id': {
      id: '/admin/lideres/$id'
      path: '/lideres/$id'
      fullPath: '/admin/lideres/$id'
      preLoaderRoute: typeof AdminLideresIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conteudo/$key': {
      id: '/admin/conteudo/$key'
      path: '/conteudo/$key'
      fullPath: '/admin/conteudo/$key'
      preLoaderRoute: typeof AdminConteudoKeyRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminConteudoKeyRoute: typeof AdminConteudoKeyRoute
  AdminLideresIdRoute: typeof AdminLideresIdRoute
  AdminConteudoIndexRoute: typeof AdminConteudoIndexRoute
  AdminLideresIndexRoute: typeof AdminLideresIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminConteudoKeyRoute: AdminConteudoKeyRoute,
  AdminLideresIdRoute: AdminLideresIdRoute,
  AdminConteudoIndexRoute: AdminConteudoIndexRoute,
  AdminLideresIndexRoute: AdminLideresIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AssessoriaRoute: AssessoriaRoute,
  AuthRoute: AuthRoute,
  ClubesRoute: ClubesRoute,
  ContatoRoute: ContatoRoute,
  DoarRoute: DoarRoute,
  EventosRoute: EventosRoute,
  ExGovernadoresRoute: ExGovernadoresRoute,
  GatRoute: GatRoute,
  GovernadorRoute: GovernadorRoute,
  HistoriaRoute: HistoriaRoute,
  LcifRoute: LcifRoute,
  LionsInternacionalRoute: LionsInternacionalRoute,
  NoticiasRoute: NoticiasRoute,
  ProjetosRoute: ProjetosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  ViceGovernador1Route: ViceGovernador1Route,
  ViceGovernador2Route: ViceGovernador2Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
