// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    const SUPABASE_URL =
      process.env.SUPABASE_URL ||
      process.env.VITE_SUPABASE_URL ||
      (typeof import.meta !== 'undefined' && (import.meta.env as any)?.VITE_SUPABASE_URL) ||
      'https://lwxnwvtdvmcnkcfcnamc.supabase.co';
    const SUPABASE_PUBLISHABLE_KEY =
      process.env.SUPABASE_PUBLISHABLE_KEY ||
      process.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
      (typeof import.meta !== 'undefined' && (import.meta.env as any)?.VITE_SUPABASE_PUBLISHABLE_KEY) ||
      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3eG53dnRkdm1jbmtjZmNuYW1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA2NzA4NTcsImV4cCI6MjA5NjI0Njg1N30.oK1D9Mwer6rppqcEQGx7QVuvR37wPiTgMKq_-ZfBVdo';
    
    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Unauthorized: No request headers available');
    }

    const authHeader = request.headers.get('authorization');
    const cookieHeader = request.headers.get('cookie') ?? '';

    // Check for dev mode cookie or token in cookies
    const isDevMode = cookieHeader.includes('gestao_dev_role') || process.env.NODE_ENV !== 'production';
    const devUserId = '00000000-0000-0000-0000-000000000001';

    let token = '';
    if (authHeader && authHeader.startsWith('Bearer ')) {
      token = authHeader.replace('Bearer ', '');
    } else {
      // Try to find token in cookies
      const match = cookieHeader.match(/sb-[^=]+-auth-token=([^;]+)/) || cookieHeader.match(/sb-access-token=([^;]+)/);
      if (match) {
        try {
          const parsed = JSON.parse(decodeURIComponent(match[1]));
          token = parsed.access_token || parsed[0] || '';
        } catch {
          token = match[1];
        }
      }
    }

    if (!token) {
      if (isDevMode) {
        // Fallback for dev mode
        const mockSupabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!);
        return next({
          context: {
            supabase: mockSupabase,
            userId: devUserId,
            claims: { sub: devUserId, role: 'authenticated' } as any,
          },
        });
      }
      throw new Error('Unauthorized: No authorization header or session cookie provided');
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Error('Unauthorized: Invalid token');
    }

    if (!data.claims.sub) {
      throw new Error('Unauthorized: No user ID found in token');
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);
